Add Assert-DockerIsRunning to RunPipeline (#2143)
### ❔What, Why & How

<!-- Include description of the changes that will help reviewers in
their task -->

Recently, we've seen a high number of failures in our CI/CD runs on
BCApps with the following failure:
```
failed to connect to the docker API at npipe:////./pipe/docker_engine; check if the path is correct and if the daemon is running: open //./pipe/docker_engine: The system cannot find the file specified.
failed to connect to the docker API at npipe:////./pipe/docker_engine; check if the path is correct and if the daemon is running: open //./pipe/docker_engine: The system cannot find the file specified.
Error: Unexpected error when running action. Error Message: Docker service is not yet ready., StackTrace: at New-BcContainer
```

As far as I can tell, the root cause is likely to be a recent update of
the GitHub images that (among other things) included an update of Docker
from 27.5.1 to 29.1.5.

**Suggested mitigation**
If Docker service isn't started, try to start it. 

Example of a test run that was "saved" by this check:
https://github.com/microsoft/BCApps/actions/runs/22388133817/job/64808833683#step:10:132

### ✅ Checklist

- [ ] Add tests (E2E, unit tests)
- [x] Update RELEASENOTES.md
- [ ] Update documentation (e.g. for new settings or scenarios)
- [ ] Add telemetry

<!-- Include more checklist entries, if needed -->

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>