AL-Go projects with large amounts of apps will fill up the environment variable (#2049)
### ❔What, Why & How

<!-- Include description of the changes that will help reviewers in
their task -->

**Repro steps:** 
1. Create an AL-Go project with a large amount of apps 
2. Create another AL-Go project where some apps have dependencies on the
apps in step 1

AL-Go will run the CI/CD in two phases. It will build a lot of apps in
the first phase, and then in phase 2 those apps will downloaded as part
of the "Download Project Dependencies" action. Here, AL-Go constructs a
list of apps and then outputs that list. Once we start the "RunPipeline"
action those lists of apps will be added as an environment variable.
Once that happens we get:
```
Error: Unexpected error when running action. Error Message: The environment block used to start a process cannot be longer than 65535 bytes.  Your environment block is 67479 bytes long.  Remove some environment variables and try again.
```
If you have a lot of apps, this list will very quickly become quite
large and will therefore fill up the environment block.

**Proposed Solution:**
Write the lists to files in a temporary folder and read the lists from
those files instead of making them environment variables.

### ✅ Checklist

- [ ] Add tests (E2E, unit tests)
- [x] Update RELEASENOTES.md
- [ ] Update documentation (e.g. for new settings or scenarios)
- [ ] Add telemetry

<!-- Include more checklist entries, if needed -->

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>
Co-authored-by: Maria Zhelezova <43066499+mazhelez@users.noreply.github.com>